name: platform_device_id
description: You can get device id from platform - linux/mac/windows/android/ios.
version: 0.2.1
homepage: https://github.com/BestBurning/platform_device_id

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  platform_device_id_platform_interface: ^0.3.0
  platform_device_id_macos: ^0.0.1
  device_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.di1shuai.platform_device_id
        pluginClass: PlatformDeviceIdPlugin
      ios:
        pluginClass: PlatformDeviceIdPlugin
      macos:
        pluginClass: PlatformDeviceIdMacosPlugin

