name: platform_device_id
description: You can get device id from platform - linux/mac/windows/android/ios/web.
version: 1.0.1
homepage: https://github.com/BestBurning/platform_device_id

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  platform_device_id_platform_interface: ^1.0.0
  platform_device_id_macos: ^1.0.0
  platform_device_id_linux: ^1.0.0
  platform_device_id_web: ^1.0.0
  platform_device_id_windows: ^1.0.0
  device_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.di1shuai.platform_device_id
        pluginClass: PlatformDeviceIdPlugin
      ios:
        pluginClass: PlatformDeviceIdPlugin
      macos:
        pluginClass: PlatformDeviceIdMacosPlugin
      linux:
        default_package: platform_device_id_linux
      web:
        default_package: platform_device_id_web
      windows:
        default_package: platform_device_id_windows

